version: "3"

volumes:
  zsh-history:
  vscode-extensions:

services:
  code:
    image: murar8/devcontainer-base:focal-latest
    init: true
    cap_add: [SYS_PTRACE]
    security_opt: [seccomp:unconfined]
    user: vscode
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - zsh-history:/home/vscode/.zsh-history
      - vscode-extensions:/home/vscode/.vscode-server/extensions
