name: release

on:
  push:
    branches: ["main"]
    tags: ["v*"]

env:
  DOCKERHUB_USERNAME: murar8
  SCRIPTS_RELEASE: v0.146.0

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu-version: ["bionic", "focal", "groovy"]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: tag-name

      - uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            SCRIPTS_RELEASE=${{ env.SCRIPTS_RELEASE }}
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
          tags: |
            murar8/devcontainer-base:${{ matrix.ubuntu-version }}-latest
            murar8/devcontainer-base:${{ matrix.ubuntu-version }}-${{ github.sha }}
            murar8/devcontainer-base:${{ matrix.ubuntu-version }}-${{ steps.tag-name.outputs.tag }}

  update-description:
    runs-on: ubuntu-latest

    needs: release

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: murar8/devcontainer-base
