name: release

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  release-base-images:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        container: ["ubuntu", "docker"]

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: tag
        run: |
          if [[ "${GITHUB_REF#refs/*/}" == "main" ]]; then
            echo "::set-output name=tag::nightly"
            echo "::set-output name=version::${GITHUB_SHA}"
          else
            echo "::set-output name=tag::latest"
            echo "::set-output name=version::${GITHUB_REF#refs/*/}"
          fi

      - id: date
        run: echo "::set-output name=date::$(date --rfc-3339=seconds)"

      - uses: docker/build-push-action@v2
        env:
          BASE_TAG: ghcr.io/${{ github.repository_owner }}/devcontainer
        with:
          push: true
          file: ./containers-base/${{ matrix.container }}/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BASE_IMAGE_TAG=${{ steps.tag.outputs.tag }}
          tags: |
            ${{ env.BASE_TAG }}-${{ matrix.container }}:${{ steps.tag.outputs.tag }}
            ${{ env.BASE_TAG }}-${{ matrix.container }}:${{ steps.tag.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.authors=Lorenzo Murarotto <lnzmrr@gmail.com>
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.tag.outputs.version }}
            org.opencontainers.image.licenses=MIT
