name: release

on: { push: { branches: ["main"] } }

env:
  SCRIPTS_RELEASE: v0.146.0

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ubuntu-version: ["bionic", "focal"]

    steps:
      - uses: actions/checkout@v2

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: tag-name
        run: |
          if [[ "${GITHUB_REF#refs/*/}" == "main" ]]; then
            echo "::set-output name=tag::nightly"
            echo "::set-output name=version::${GITHUB_SHA}"
          else
            echo "::set-output name=tag::latest"
            echo "::set-output name=version::${GITHUB_REF#refs/*/}"
          fi

      - id: date
        run: echo "::set-output name=date::$(date --rfc-3339=seconds)"

      - uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            SCRIPTS_RELEASE=${{ env.SCRIPTS_RELEASE }}
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
          tags: |
            ghcr.io/murar8/devcontainer-base:${{ matrix.ubuntu-version }}-${{ steps.tag-name.outputs.tag }}
            ghcr.io/murar8/devcontainer-base:${{ matrix.ubuntu-version }}-${{ steps.tag-name.outputs.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.date }}
            org.opencontainers.image.authors="Lorenzo Murarotto <lnzmrr@gmail.com>"
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ steps.tag-name.outputs.tag }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses="MIT"
